services:
  db:
    image: postgres:14.5
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - POSTGRES_DATABASE=rails_api
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Aa123456
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./backend_api
    environment:
      - PORT=3000
    volumes:
      - ./backend_api:/webapp
    ports:
      - "3000:3000" # use port that you want to in your local instead of 3000
    depends_on:
      - db
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./vue_frontend
      dockerfile: Dockerfile
    volumes:
       - ./vue_frontend:/app
       - /app/node_modules
    ports:
      - "8080:3000"
volumes:
  db:
    driver: local
