version: '2.4.1'
services:
  db:
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=rails_api
      - MYSQL_ROOT_PASSWORD=Aa123456
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./backend_api
    environment:
      - PORT=3000
    volumes:
      - ./backend_api:/webapp
    ports:
      - "3000:3000" # use port that you want to in your local instead of 3000
    depends_on:
      - db
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./vue_frontend
      dockerfile: Dockerfile
    volumes:
       - ./vue_frontend:/app
       - /app/node_modules
    ports:
      - "8080:3000"
volumes:
  db:
    driver: local